# Generated by Django 5.2.3 on 2025-07-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sellerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
