# Generated by Django 5.2.3 on 2025-07-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=10),
        ),
    ]
